#!/bin/bash

OBJDIR="$1"
LIBFILE="$2"
LIBS="$3"

# Which source produced this binary.  Taken from the environment rather than a
# positional argument, because the Makefile's own call already passes four and
# this has to stay compatible with it.  "unknown" is what a build outside a
# checkout gets, and is honest about it.
BUILDID="${S4_BUILD_ID:-unknown}"

# This fork's own version, from the VERSION file so that the C source, the
# distribution metadata and the tag all read the same number.  Upstream's
# release is recorded separately rather than reused: it has not moved since
# 2018 and this line has, so claiming to be 1.1 would be a claim about
# behaviour that is no longer true.
# Named version.txt, not VERSION: the repository root is on the include path
# (-I.), the filesystem here is case-insensitive, and a file called VERSION is
# what the C++ standard header <version> resolves to.  Every C++ translation
# unit that reaches <limits> stops compiling.
FORKVER="${S4_FORK_VERSION:-$(cat "$(dirname "$0")/version.txt" 2>/dev/null || echo 0.0.0)}"

cat <<SETUPPY > setup.py
# Generated by gensetup.py.sh -- do not edit by hand.
try:
	from setuptools import setup, Extension
except ImportError:
	from distutils.core import setup, Extension

# The Makefile knows which BLAS/LAPACK/FFTW/pthread/CHOLMOD/MPI libraries this
# build was configured against; it hands them over as a single link line. Split
# it into the pieces distutils/setuptools expects rather than dropping it, since
# libS4.a leaves those symbols undefined and the extension fails to import
# without them.
_libs = []
_lib_dirs = []
_extra = []
for _tok in '''$LIBS'''.split():
	if _tok.startswith('-L'):
		_lib_dirs.append(_tok[2:])
	elif _tok.startswith('-l'):
		_libs.append(_tok[2:])
	else:
		_extra.append(_tok)

S4module = Extension('S4',
	sources = [
		'S4/main_python.c'
	],
	libraries = _libs,
	library_dirs = _lib_dirs,
	extra_objects = [
		'$LIBFILE'
	],
	extra_link_args = _extra,
	extra_compile_args = ['-DS4_BUILD_ID="$BUILDID"',
		'-DS4_FORK_VERSION="$FORKVER"']
)

setup(name = 's4-fieldalgo',
	version = '$FORKVER+$BUILDID',
	description = 'S4 (Stanford Stratified Structure Solver), fieldalgo line: '
	              'Fourier Modal Method, forked from victorliu/S4 1.1',
	ext_modules = [S4module]
)
SETUPPY
