#!/bin/bash

OBJDIR="$1"
LIBFILE="$2"
LIBS="$3"

cat <<SETUPPY > setup.py
# Generated by gensetup.py.sh -- do not edit by hand.
try:
	from setuptools import setup, Extension
except ImportError:
	from distutils.core import setup, Extension

# The Makefile knows which BLAS/LAPACK/FFTW/pthread/CHOLMOD/MPI libraries this
# build was configured against; it hands them over as a single link line. Split
# it into the pieces distutils/setuptools expects rather than dropping it, since
# libS4.a leaves those symbols undefined and the extension fails to import
# without them.
_libs = []
_lib_dirs = []
_extra = []
for _tok in '''$LIBS'''.split():
	if _tok.startswith('-L'):
		_lib_dirs.append(_tok[2:])
	elif _tok.startswith('-l'):
		_libs.append(_tok[2:])
	else:
		_extra.append(_tok)

S4module = Extension('S4',
	sources = [
		'S4/main_python.c'
	],
	libraries = _libs,
	library_dirs = _lib_dirs,
	extra_objects = [
		'$LIBFILE'
	],
	extra_link_args = _extra
)

setup(name = 'S4',
	version = '1.1',
	description = 'Stanford Stratified Structure Solver (S4): Fourier Modal Method',
	ext_modules = [S4module]
)
SETUPPY
